import { useEffect, useRef, useState, useId } from "react"
import { AlertTriangle } from "lucide-react"

interface MermaidDiagramProps {
  chart: string
  className?: string
}

/** Renders a Mermaid diagram definition (e.g. the mind maps generated by Smart Notes)
 * as an actual SVG diagram. The `mermaid` package is already a project dependency —
 * this component is what actually puts it to use, instead of dumping raw diagram
 * source as plain text. */
export function MermaidDiagram({ chart, className }: MermaidDiagramProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [error, setError] = useState<string | null>(null)
  const id = useId().replace(/:/g, "-")

  useEffect(() => {
    let cancelled = false

    async function render() {
      if (!chart?.trim()) return
      try {
        const mermaid = (await import("mermaid")).default
        mermaid.initialize({
          startOnLoad: false,
          theme: document.documentElement.classList.contains("dark") ? "dark" : "default",
          securityLevel: "strict",
        })
        const { svg } = await mermaid.render(`mermaid-${id}`, chart.trim())
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg
          setError(null)
        }
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : "Could not render diagram")
      }
    }

    render()
    return () => { cancelled = true }
  }, [chart, id])

  if (error) {
    return (
      <div className={`flex items-start gap-2 text-sm text-muted-foreground bg-muted/40 rounded-lg p-4 ${className ?? ""}`}>
        <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5 text-amber-500" />
        <div>
          <p>Couldn't render this diagram.</p>
          <pre className="text-xs mt-2 overflow-x-auto whitespace-pre-wrap">{chart}</pre>
        </div>
      </div>
    )
  }

  return <div ref={containerRef} className={`overflow-x-auto flex justify-center [&_svg]:max-w-full ${className ?? ""}`} />
}
